#!/usr/bin/env python3
"""Pack viewer/out/ into a C++ header of gzip-compressed files.

Usage: embed_viewer.py --out-dir viewer/out --output generated.hpp

Each file is gzip-compressed (stdlib gzip, mtime=0 for reproducibility),
sha256-hashed (strong ETag over the stored bytes), and annotated with a
MIME type + immutable bit. The viewer server (core/view/view.cpp) serves
the stored bytes with Content-Encoding: gzip, the ETag, and immutable
caching for hashed assets. MIME map must match mimeFor() in view.cpp.
"""
import argparse
import gzip
import hashlib
import os
import re

MIME = {
    ".html": "text/html; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".mjs": "text/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".json": "application/json",
    ".map": "application/json",
    ".idx": "application/json",
    ".jsonl": "application/x-ndjson",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".ico": "image/x-icon",
    ".txt": "text/plain; charset=utf-8",
    ".log": "text/plain; charset=utf-8",
    ".sse": "text/event-stream",
}

HASHED = re.compile(r"-[0-9a-fA-F]{8,}\.[^./]+$")


def mime_for(url_path):
    _, ext = os.path.splitext(url_path)
    return MIME.get(ext.lower(), "application/octet-stream")


def is_immutable(url_path):
    if url_path.startswith("/_next/static/"):
        return True
    return HASHED.search(url_path) is not None


def cpp_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--output", required=True)
    args = ap.parse_args()

    rels = []
    for root, _, files in os.walk(args.out_dir):
        for fn in files:
            full = os.path.join(root, fn)
            rels.append(os.path.relpath(full, args.out_dir).replace(os.sep, "/"))
    rels.sort()

    arrays = []
    entries = []
    for i, rel in enumerate(rels):
        url = "/" + rel
        with open(os.path.join(args.out_dir, rel), "rb") as f:
            raw = f.read()
        gz = gzip.compress(raw, compresslevel=9, mtime=0)
        # Tiny files where gzip hurts are stored raw (etag still strong).
        stored, zipped = (gz, True) if len(gz) < len(raw) else (raw, False)
        etag = hashlib.sha256(stored).hexdigest()
        if stored:
            hexes = ",".join("0x" + stored[j:j+1].hex() for j in range(len(stored)))
            arrays.append(
                "static const unsigned char kViewerFile%d[] = {%s};\n" % (i, hexes))
        else:
            # Empty initializer lists are rejected by strict compilers.
            arrays.append(
                "static const unsigned char kViewerFile%d[1] = {0};\n" % i)
        entries.append(
            "  {%s, kViewerFile%d, %dul, %dul, %d, \"%s\", %s, %d},\n"
            % (cpp_str(url), i, len(stored), len(raw), 1 if zipped else 0,
               etag, cpp_str(mime_for(url)), 1 if is_immutable(url) else 0))

    with open(args.output, "w") as f:
        f.write("// Generated by cmake/embed_viewer.py from viewer/out/ — do not edit.\n"
                "// Data is gzip-compressed (mtime=0); etag is sha256 of stored bytes.\n"
                "#pragma once\n"
                "namespace snowglobe::viewer_data {\n"
                "struct EmbeddedFile {\n"
                "  const char* path;\n"
                "  const unsigned char* data;\n"
                "  unsigned long size;\n"
                "  unsigned long orig_size;\n"
                "  int gzipped;\n"
                "  const char* etag;\n"
                "  const char* mime;\n"
                "  int immutable;\n"
                "};\n")
        f.write("".join(arrays))
        f.write("static const EmbeddedFile kFiles[] = {\n")
        f.write("".join(entries))
        f.write("};\n")
        f.write("static const unsigned long kFileCount = %d;\n" % len(rels))
        f.write("}  // namespace snowglobe::viewer_data\n")
    print("embed_viewer: %d files -> %s" % (len(rels), args.output))


if __name__ == "__main__":
    main()
