# cmake/embed_viewer.cmake — pack viewer/out/ into a C++ header (pure CMake,
# no extra tools). Run at build time via add_custom_command, so edits under
# viewer/ rebuild the binary with no reconfigure.
#
# Args: -DVIEWER_OUT_DIR=<viewer/out> -DOUTPUT_HPP=<generated header>
file(GLOB_RECURSE _vf RELATIVE "${VIEWER_OUT_DIR}" "${VIEWER_OUT_DIR}/*")
list(SORT _vf)
set(_arrays "")
set(_entries "")
set(_idx 0)
foreach(_rel IN LISTS _vf)
  string(REPLACE "\\" "/" _url "/${_rel}")
  file(READ "${VIEWER_OUT_DIR}/${_rel}" _hex HEX)
  if(_hex STREQUAL "")
    # Zero-byte file: emit a 1-byte array but record size 0 (empty
    # initializers deduce no size and are rejected by strict compilers).
    string(APPEND _arrays "static const unsigned char kViewerFile${_idx}[1] = {0};\n")
    string(APPEND _entries "  {\"${_url}\", kViewerFile${_idx}, 0},\n")
  else()
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _list "${_hex}")
    string(APPEND _arrays "static const unsigned char kViewerFile${_idx}[] = {${_list}};\n")
    string(APPEND _entries "  {\"${_url}\", kViewerFile${_idx}, sizeof(kViewerFile${_idx})},\n")
  endif()
  math(EXPR _idx "${_idx} + 1")
endforeach()
file(WRITE "${OUTPUT_HPP}"
  "// Generated by cmake/embed_viewer.cmake from viewer/out/ — do not edit.\n"
  "// Each file is one byte array; the viewer server looks them up by URL path.\n"
  "#pragma once\n"
  "namespace snowglobe::viewer_data {\n"
  "struct EmbeddedFile {\n"
  "  const char* path;\n"
  "  const unsigned char* data;\n"
  "  unsigned long size;\n"
  "};\n"
  "${_arrays}"
  "static const EmbeddedFile kFiles[] = {\n"
  "${_entries}"
  "};\n"
  "static const unsigned long kFileCount = ${_idx};\n"
  "} // namespace snowglobe::viewer_data\n")
